version: "2"
services:
  app:
    build: ./
#    links:
#      - db
    ports:
      - "5000:5000"
    network_mode: "host"

#  db:
#    image: mysql
#    #restart: always
#    command: --default-authentication-plugin=mysql_native_password
#    ports:
#      - "6603:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - ...
